/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulationRouteImport } from './routes/app.simulation'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCalculatorsRouteImport } from './routes/app.calculators'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiRagQueryRouteImport } from './routes/api.rag.query'
import { Route as ApiRagIndexFileRouteImport } from './routes/api.rag.index-file'
import { Route as ApiCreditsRewardRouteImport } from './routes/api.credits.reward'
import { Route as ApiCreditsBalanceRouteImport } from './routes/api.credits.balance'
import { Route as ApiBillingVerifyRouteImport } from './routes/api.billing.verify'
import { Route as ApiBillingCreateOrderRouteImport } from './routes/api.billing.create-order'
import { Route as ApiAdminContentRouteImport } from './routes/api.admin.content'
import { Route as ApiAdminAnalyticsRouteImport } from './routes/api.admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulationRoute = AppSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsRoute = AppCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagQueryRoute = ApiRagQueryRouteImport.update({
  id: '/api/rag/query',
  path: '/api/rag/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagIndexFileRoute = ApiRagIndexFileRouteImport.update({
  id: '/api/rag/index-file',
  path: '/api/rag/index-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsRewardRoute = ApiCreditsRewardRouteImport.update({
  id: '/api/credits/reward',
  path: '/api/credits/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsBalanceRoute = ApiCreditsBalanceRouteImport.update({
  id: '/api/credits/balance',
  path: '/api/credits/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingVerifyRoute = ApiBillingVerifyRouteImport.update({
  id: '/api/billing/verify',
  path: '/api/billing/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCreateOrderRoute = ApiBillingCreateOrderRouteImport.update({
  id: '/api/billing/create-order',
  path: '/api/billing/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnalyticsRoute = ApiAdminAnalyticsRouteImport.update({
  id: '/api/admin/analytics',
  path: '/api/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calculators': typeof AppCalculatorsRoute
  '/app/chat': typeof AppChatRoute
  '/app/files': typeof AppFilesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/billing/create-order': typeof ApiBillingCreateOrderRoute
  '/api/billing/verify': typeof ApiBillingVerifyRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/reward': typeof ApiCreditsRewardRoute
  '/api/rag/index-file': typeof ApiRagIndexFileRoute
  '/api/rag/query': typeof ApiRagQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calculators': typeof AppCalculatorsRoute
  '/app/chat': typeof AppChatRoute
  '/app/files': typeof AppFilesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/billing/create-order': typeof ApiBillingCreateOrderRoute
  '/api/billing/verify': typeof ApiBillingVerifyRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/reward': typeof ApiCreditsRewardRoute
  '/api/rag/index-file': typeof ApiRagIndexFileRoute
  '/api/rag/query': typeof ApiRagQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calculators': typeof AppCalculatorsRoute
  '/app/chat': typeof AppChatRoute
  '/app/files': typeof AppFilesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulation': typeof AppSimulationRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/billing/create-order': typeof ApiBillingCreateOrderRoute
  '/api/billing/verify': typeof ApiBillingVerifyRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/reward': typeof ApiCreditsRewardRoute
  '/api/rag/index-file': typeof ApiRagIndexFileRoute
  '/api/rag/query': typeof ApiRagQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/billing'
    | '/app/calculators'
    | '/app/chat'
    | '/app/files'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/research'
    | '/app/settings'
    | '/app/simulation'
    | '/api/admin/analytics'
    | '/api/admin/content'
    | '/api/billing/create-order'
    | '/api/billing/verify'
    | '/api/credits/balance'
    | '/api/credits/reward'
    | '/api/rag/index-file'
    | '/api/rag/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/billing'
    | '/app/calculators'
    | '/app/chat'
    | '/app/files'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/research'
    | '/app/settings'
    | '/app/simulation'
    | '/api/admin/analytics'
    | '/api/admin/content'
    | '/api/billing/create-order'
    | '/api/billing/verify'
    | '/api/credits/balance'
    | '/api/credits/reward'
    | '/api/rag/index-file'
    | '/api/rag/query'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/admin'
    | '/app/billing'
    | '/app/calculators'
    | '/app/chat'
    | '/app/files'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/research'
    | '/app/settings'
    | '/app/simulation'
    | '/api/admin/analytics'
    | '/api/admin/content'
    | '/api/billing/create-order'
    | '/api/billing/verify'
    | '/api/credits/balance'
    | '/api/credits/reward'
    | '/api/rag/index-file'
    | '/api/rag/query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAdminAnalyticsRoute: typeof ApiAdminAnalyticsRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiBillingCreateOrderRoute: typeof ApiBillingCreateOrderRoute
  ApiBillingVerifyRoute: typeof ApiBillingVerifyRoute
  ApiCreditsBalanceRoute: typeof ApiCreditsBalanceRoute
  ApiCreditsRewardRoute: typeof ApiCreditsRewardRoute
  ApiRagIndexFileRoute: typeof ApiRagIndexFileRoute
  ApiRagQueryRoute: typeof ApiRagQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/simulation': {
      id: '/app/simulation'
      path: '/simulation'
      fullPath: '/app/simulation'
      preLoaderRoute: typeof AppSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators': {
      id: '/app/calculators'
      path: '/calculators'
      fullPath: '/app/calculators'
      preLoaderRoute: typeof AppCalculatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/query': {
      id: '/api/rag/query'
      path: '/api/rag/query'
      fullPath: '/api/rag/query'
      preLoaderRoute: typeof ApiRagQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/index-file': {
      id: '/api/rag/index-file'
      path: '/api/rag/index-file'
      fullPath: '/api/rag/index-file'
      preLoaderRoute: typeof ApiRagIndexFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/reward': {
      id: '/api/credits/reward'
      path: '/api/credits/reward'
      fullPath: '/api/credits/reward'
      preLoaderRoute: typeof ApiCreditsRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/balance': {
      id: '/api/credits/balance'
      path: '/api/credits/balance'
      fullPath: '/api/credits/balance'
      preLoaderRoute: typeof ApiCreditsBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/verify': {
      id: '/api/billing/verify'
      path: '/api/billing/verify'
      fullPath: '/api/billing/verify'
      preLoaderRoute: typeof ApiBillingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/create-order': {
      id: '/api/billing/create-order'
      path: '/api/billing/create-order'
      fullPath: '/api/billing/create-order'
      preLoaderRoute: typeof ApiBillingCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics': {
      id: '/api/admin/analytics'
      path: '/api/admin/analytics'
      fullPath: '/api/admin/analytics'
      preLoaderRoute: typeof ApiAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalculatorsRoute: typeof AppCalculatorsRoute
  AppChatRoute: typeof AppChatRoute
  AppFilesRoute: typeof AppFilesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulationRoute: typeof AppSimulationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalculatorsRoute: AppCalculatorsRoute,
  AppChatRoute: AppChatRoute,
  AppFilesRoute: AppFilesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppResearchRoute: AppResearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulationRoute: AppSimulationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAdminAnalyticsRoute: ApiAdminAnalyticsRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiBillingCreateOrderRoute: ApiBillingCreateOrderRoute,
  ApiBillingVerifyRoute: ApiBillingVerifyRoute,
  ApiCreditsBalanceRoute: ApiCreditsBalanceRoute,
  ApiCreditsRewardRoute: ApiCreditsRewardRoute,
  ApiRagIndexFileRoute: ApiRagIndexFileRoute,
  ApiRagQueryRoute: ApiRagQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
